version: '2'
services:
  javagaugeselenium:
    container_name: javagaugeselenium  
    build: .
  firefox:
    image: selenium/node-firefox
    #image: selenium/node-firefox-debug
    #vnc port 5900 pw: secret
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    ports:
      - "5900:5900"

  chrome:
    image: selenium/node-chrome
    #image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    ports:
      - "5901:5900"

  hub:
    container_name: browsertestframework_hub
    image: selenium/hub
    ports:
      - "4444:4444"